### ISSUE TITLE
Differences with older version & micropython support

### ISSUE THREAD

**Issue by bsecker** [iot-for-all/iotc-python-client#1]
Hey, I was wondering if you could provide some clarification between this version and [0.3.6 on pypi](https://pypi.org/project/iotc/0.3.6/), which appears to be double the length of source code.

does this still have support for Micropython?

**Comment by lucadruda** [comment]
Version 0.3.6 is still using old format with simple mqtt (thus working with micropython as well) and no async support.
From version 1.x we're wrapping official Azure IoT SDK in order to support multiple protocols, async communication and retry logic.
Also we added tests and more detailed documentation.
There will be a separate release for Micropython under upypi in the next days. Meanwhile you can continue to use last supported version (0.3.9) still working on constrained devices.

**Comment by bsecker** [comment]
Awesome! Looking forward to the release :-) Will the source be released under the [iot-for-all](https://github.com/iot-for-all) group?

**Comment by lucadruda** [comment]
Yes it will.
